train:
  ner:
    output_dir: "big-ner"
    evaluation_strategy: "steps"
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    num_train_epochs: 3
    logging_steps: 20000
    weight_decay: 0.01
    load_best_model_at_end: True
    save_total_limit: 1
    warmup_steps: 500
    save_steps: 20000

  re:
    output_dir: "results"
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 64
    num_train_epochs: 3
    weight_decay: 0.01
    save_total_limit: 1
    warmup_steps: 500
    save_strategy: "no"
    load_best_model_at_end: False