train:
  ner:
    output_dir: "./training_output/m-bert_my_ner_de_en_corpora_output"
    evaluation_strategy: "steps"
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    num_train_epochs: 6
    logging_steps: 800
    train_val_split: 0.2
    weight_decay: 1e-3
    learning_rate: 2e-5